- project:
    check: &ci
      jobs:
        - shake-factory-test
        - shake-factory-docs
        - npm-test:
            files:
              - package.json
              - bsconfig.json
              - src/.*
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py36:
            nodeset: python-latest-pod
    gate: *ci
    post:
      jobs:
        - shake-factory-publish-docs
    release:
      jobs:
        - upload-pypi
