- project:
    check: &ci
      jobs:
        - shake-factory-test:
            required-projects:
              - software-factory/dhall-zuul
        - shake-factory-docs
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py36:
            nodeset: python-latest-pod
    gate: *ci
    post:
      jobs:
        - shake-factory-publish-docs
    release:
      jobs:
        - upload-pypi
